### PR TITLE
Apps updated to version of 2024-01-27

### PR DESCRIPTION
**Pull request by FaySmash**

### CODE REVIEW

**Comment by amartinz** [comment]
I can not remember we have published a new OTA.

Can you please explain these changes in more detail?

**Comment by FaySmash** [comment]
> I can not remember we have published a new OTA.
> 
> Can you please explain these changes in more detail?

Well, the latest changes in the lineage-20 branch were from 4 months ago but the latest Lineage OS 20 release was on the 10th of February (but the latest ZIP I saved was from the 27th of January). I extracted the blobs of this ZIP and compared it to the ones in this repos lineage-20 branch and while there were no significant changes, those Apps were updated in the meantime (could only verify the changes in a HEX Editor).
I uploaded the Apps I extracted here because it seemed like the lineage-20 branch won't receive any further updates and I at least wanted to upload the latest blobs of LineageOS 20 available to me.

**Comment by amartinz** [comment]
You mean you extracted these from a lineage OTA?

The extraction scripts should only be run against OTAs from stock whenever there are updates.
I am actually doing this directly from the signed target files whenever we publish an OTA.

I think the changes you pushed is churn caused by different signing of lineage and there are no actual changes of these apks.

**Comment by FaySmash** [comment]
> You mean you extracted these from a lineage OTA?
> 
> The extraction scripts should only be run against OTAs from stock whenever there are updates. I am actually doing this directly from the signed target files whenever we publish an OTA.
> 
> I think the changes you pushed is churn caused by different signing of lineage and there are no actual changes of these apks.

Ahh understood, my bad. I hope that if there are any new OTAs in the future, the linage-20 branch will also get updated if applicable 🙂

**Comment by amartinz** [comment]
> Ahh understood, my bad. I hope that if there are any new OTAs in the future, the linage-20 branch will also get updated if applicable 🙂

Sure, i keep updating `lineage-20` as well, because `sos-5.x` is based on it and it would be just a matter of uploading the commit anyways :)

**Pull request closed without merging**
